version: '3.4'

services:
  todoapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
    

  webapp1:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
    